accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
	path('logout/', views.logoutUser, name="logout"),
]

posts/urls.py
from django.urls import path
from .views import post_create_and_list_view, like_unlike_post, post_serialized_view

app_name = 'posts'

urlpatterns = [
    path('', post_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('serialized/', post_serialized_view, name='serialized-view'),
]

profiles/urls.py
from django.urls import path
from .views import my_profile_view

app_name = 'profiles'

urlpatterns = [
    path('myprofile', my_profile_view, name='my-profile-view')
]

socialapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', home_view, name='home_view'),
    path('', include('profiles.urls', namespace='profiles')),
    path('', include('posts.urls', namespace='posts')),
    path('', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/main/home.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}
{{text}}
<br>
{{user}}
{% endblock content %}

{% block scripts %}

{% endblock scripts %}

templates/main/navbar.html
<div class="ui inverted menu nav mb-7">
    <div class="ui container">
      <a href="{% url 'posts:main-post-view' %}" class="item">
          <h2>App</h2>
      </a>
      {% if request.user.is_authenticated %}
      <a style="font-weight:bold; font-size:16px" href="{% url 'posts:main-post-view' %}" class="item">
          Home
      </a>
      {% endif %}
  
      <div class="right menu">
          {% if request.user.is_authenticated %}
        
              <a style="font-weight:bold; font-size:16px" href="{% url 'profiles:my-profile-view' %}" class="item">
                   {{ request.user }}'s Profile
              </a>
  
              <a style="font-weight:bold; font-size:16px" href="{% url 'accounts:logout' %}" class="ui item">
                  Logout
              </a>
          {% else %}
          <a style="font-weight:bold" href="{% url 'accounts:login' %}" class="ui item">
                  Login
              </a>
          {% endif %}
      </div>
    </div>
  </div>