posts/urls.py
from django.urls import path
from .views import post_create_and_list_view, like_unlike_post, post_serialized_view

app_name = 'posts'

urlpatterns = [
    path('', post_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('serialized/', post_serialized_view, name='serialized-view'),
]

socialapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', home_view, name='home_view'),
    path('', include('profiles.urls', namespace='profiles')),
    path('', include('posts.urls', namespace='posts')),
    path('', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile

class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='posts', validators=[FileExtensionValidator(['png','jpg','jpeg'])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts') 

    def __str__(self):
        return str(self.content[:20])

    def num_likes(self):
        return self.liked.all().count()
    
    class Meta:
        ordering = ('-created',)

LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

posts/forms.py
from django import forms
from .models import Post

class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':3}))
    class Meta:
        model = Post
        fields = ('content', 'image')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Like
from profiles.models import Profile
from .forms import PostModelForm
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required

@login_required(login_url='accounts:login')
def post_create_and_list_view(request):
    qset = Post.objects.all()
    profile = Profile.objects.get(user=request.user)

    p_form = PostModelForm(request.POST or None, request.FILES or None)
    post_added = False

    profile = Profile.objects.get(user=request.user)
    
    if p_form.is_valid():
        instance = p_form.save(commit=False)
        instance.author = profile
        instance.save()
        p_form = PostModelForm()
        post_added = True

    context = {
        'qset' : qset,
        'profile' : profile,
        'p_form' : p_form,
        'post_added' : post_added
    }

    return render(request, 'posts/main.html',context)

@login_required(login_url='accounts:login')
def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)
        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created:
            if like.value=='Like':
                like.value='Unlike'
            else:
                like.value='Like'
        else:
            like.value='Like'
            post_obj.save()
            like.save()
    
    # return redirect('posts:main-post-view')
        return HttpResponse()

def post_serialized_view(request):
    data = list(Post.objects.values())
    return JsonResponse(data, safe=False)

posts/templates/posts/main.html
{% extends 'base.html' %}

{% block title %}main page{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="eleven wide column">
        {% for obj in qset %}

        <div class="ui fluid card">
            <div class="content">
                <img class="ui avatar image" src={{obj.author.avatar.url}}> 
                {{ obj.author.user }} - {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <p> {{ obj.content }} </p>
                <div class="right floated">
                    <form method="POST" action="{% url 'posts:like-post-view' %}" class='like-form' id='{{obj.id}}'>
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        <button class="ui primary button like-btn{{obj.id}}">
                            {% if profile in obj.liked.all %}
                            Unlike
                            {% else %}
                            Like
                            {% endif %}
                        </button>
                        <span class="like-count{{obj.id}}" id="{{obj.num_likes}}">{{obj.num_likes}}</span>
                    </form>
                </div>
            </div>
        </div>


        {% endfor %}
    </div>
    <div class="five wide column">
        <div class="ui segment">
            {% if post_added %}
                <div class="ui green message">Post added</div>
            {% endif %}
            <form action="" method="POST" class='ui form' enctype="multipart/form-data">
                {% csrf_token %}
                {{p_form}}
                <br><br>
                <button type='submit' name="submit_p_form" class="ui positive button w-full mt-5">Post</button>
            </form>
        </div> 
</div>
{% endblock content %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $('.like-form').submit(function(e){
                e.preventDefault()
                const post_id = $(this).attr('id')
                const likeText = $(`.like-btn${post_id}`).text()
                const trim = $.trim(likeText)
                const url = $('.like-form').attr('action')
                var count = parseInt($(`.like-count${post_id}`).text())

                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'post_id': post_id,
                    },

                    success: function() {
                        console.log('success')

                        $.ajax({
                            type: 'GET',
                            url: '/serialized/',
                            success: function(response) {
                                console.log(response)
                                $.each(response, function(index, element){
                                    console.log(index)
                                    console.log(element.content)
                                    if (post_id == element.id) {
                                        if (trim == 'Like') {
                                            count = count + 1
                                            console.log('unlike')
                                            $(`.like-btn${post_id}`).html('Unlike')
                                            $(`.like-count${post_id}`).html(count)
                                        } else if (trim == 'Unlike') {
                                            count = count - 1
                                            console.log('like')
                                            $(`.like-btn${post_id}`).html('Like')
                                            $(`.like-count${post_id}`).html(count)
                                        } else {
                                            console.log('oops')
                                        }
                                        console.log('Count')
                                        console.log(count)
                                        
                                    }
                                })
                            },
                            error: function(error){
                                console.log('error')
                            }
                        })
                    },
                    error: function(error){
                        console.log('error')
                    }
                })
            })
        })
    </script>

{% endblock scripts %}